hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

quotes/urls.py
from django.urls import path

from . import views

app_name= "quotes"

urlpatterns = [
    path('', views.main, name = "root"),
    path('<int:page>', views.main, name = "root_paginate"),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('tags/<int:tag_id>', views.tags, name='tags'),
    path('addtag/', views.addtag, name='addtag'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addquote, name='addquote'),
]
 

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag, related_name='posts')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

quotes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(min_length=3,
                    max_length=50, required=True,
                    widget=TextInput(attrs={"class": "form-control custom-border", "placeholder": "Enter a tag"}))
    
    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_location = CharField(min_length=3, max_length=150, required=True, widget=TextInput())
    description = TextInput()

    
    class Meta:
        model = Author
        fields = ['fullname','born_date','born_location','description']


class QuoteForm(ModelForm):

    quote = TextInput()

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags','author']

quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Count

from .models import Author, Tag, Quote
from .forms import TagForm, AuthorForm, QuoteForm

from django.contrib.auth.decorators import login_required

def main(request, page = 1):
    quotes = Quote.objects.all()
    top_tags = Tag.objects.annotate(num_posts=Count('posts')).order_by('-num_posts')[:10]
    print(top_tags)
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
   
    return render(request,'quotes/index.html', context={'quotes':quotes_on_page, 'top_tags': top_tags})

def detail(request, quote_id):
    author = get_object_or_404(Author, pk=quote_id)
    return render(request, 'quotes/detail.html', {"author": author})

def tags(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    return render(request, 'quotes/tags.html', context={"quotes": quotes, "tag": tag})

@login_required
def addtag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/addtag.html', {'form': form})

    return render(request, 'quotes/addtag.html', {'form': TagForm()})

@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/addauthor.html', {'form': form})

    return render(request, 'quotes/addauthor.html', {'form': AuthorForm()})


@login_required
def addquote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_note = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            choice_author = Author.objects.filter(fullname__in=request.POST.getlist('authorid'))
            for tag in choice_tags.iterator():
                print(tag)
                new_note.tags.add(tag)
            print(choice_author)
            for author in choice_author.iterator():
                print(author)
                print(author.id)
                print(new_note.author)
                new_note.author = author
                print(new_note.author)
                print(new_note.author_id)


            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/addquote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'quotes/addquote.html', {"tags": tags, "authors": authors,'form': QuoteForm()})

quotes/templates/quotes/addauthor.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:addauthor' %}">
    {% csrf_token %}
    <h2>Add Author</h2><br>
    <div style="padding: 10px">
        <label>Enter the author name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>


{% endblock %}

quotes/templates/quotes/addquote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:addquote' %}">
    {% csrf_token %}
    <h2>Add Quote</h2>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div style="padding: 10px">
        <label> Select author:
            <select name="authorid" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-danger"" style="margin-left: 350px;">Reset</button>
    </div>
</form>
{% endblock %}

quotes/templates/quotes/addtag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:addtag' %}">
    {% csrf_token %}
    <div>
        <div style="margin-left: 28px;">
            <h2 class="mb-3">Add Tag</h2>
            <label>Enter the tag name:
                {{form.name}}
            </label>
            <span>{{ form.errors.name }}</span>
        </div>
        <br>
        <div class="grid" style="margin-left: 28px;">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-danger"" style="margin-left: 350px;">Reset</button>
        </div>
    </div>
</form>

{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>Django Quotes App</title>
</head>
<body>

    <div class="container">
        <div class="row header-box pt-4">
            <div class="col-md-9">
                <h1>
                    <a href="/" style="text-decoration: none">Django Quotes App</a>
                </h1>
                <hr class="quote-line">

            </div>
            <div class="col-md-2">
                {% if user.is_authenticated %}

                <p>
                    Welcome <b>{{ user.username }}!</b><br>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary"><b>Logout</b></a>
                </p>

                <div class="d-grid gap-1">
                        <a href="{% url 'quotes:addquote' %}" class="btn btn-primary" 
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Add Quote</a>
                        
                        <a href="{% url 'quotes:addauthor' %}" class="btn btn-primary"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Add Author</a>
                        
                        <a href="{% url 'quotes:addtag' %}" class="btn btn-primary"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Add Tag</a>
        
                </div>
                
                {% else %}
                <p>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Sign Up</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                </p>
                {% endif %}
            </div>
        </div>
    
        {% block content %} {% endblock %}

    </div>

</body>
</html>

quotes/templates/quotes/detail.html
{% extends 'quotes/base.html' %}


{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>


{% endblock %}

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% load extract_id %}

{% block content %}

 

<div class="row">
    <div class="col-md-4">
        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="{% url 'quotes:detail' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {%for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tags' tag.id %}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}

    <div class="col-md-8 tags-box">
        
            <h2>Top Ten tags</h2>
            
            {% for tag in top_tags %}

            <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="{% url 'quotes:tags' tag.id %}">{{ tag.name }}</a>
            </span>
            
            {% endfor %}
            
        
    </div>

        
            <nav>
                <ul class="pager">
            
                    <li class="previous">
                        <a class = "{% if not quotes.has_previous %} disabled {% endif %}" 
                            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                                <span aria-hidden="true">←</span> Previous</a>
                    </li>
                    
                    
                    <li class="next">
                        <a class = "{% if not quotes.has_next %} disabled {% endif %}" 
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span></a>
                    </li>
                    
                </ul>
            </nav>
        </div>
    
</div>

{% endblock %}

quotes/templates/quotes/tags.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<h3>Viewing tag: <a href="{% url 'quotes:tags' tag.id %}">{{tag.name}}</a></h3>

{% for quote in quotes %}
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
  

    <span class="text" itemprop="text">{{quote.quote}}</span>
    <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
    <a href="{% url 'quotes:detail' quote.author.id %}">(about)</a>
    </span>
    <div class="tags">
        Tags:
        {%for tag in quote.tags.all %}
        <a class="tag" href="{% url 'quotes:tags' tag.id %}">{{tag.name}}</a>
        {% endfor %}
        
    </div>
   
</div>
{% endfor %}
{% endblock %}